/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 02 22:35:35 GMT 2024
 */

package org.apache.commons.geometry.core.internal;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.geometry.core.internal.GeometryInternalUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GeometryInternalUtils_ESTest extends GeometryInternalUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object object0 = new Object();
      boolean boolean0 = GeometryInternalUtils.sameInstance(object0, object0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object object0 = new Object();
      Object object1 = new Object();
      boolean boolean0 = GeometryInternalUtils.sameInstance(object0, object1);
      assertFalse(boolean0);
  }
}
